services:
  gemma-api:
    build:
      context: .
    container_name: gemma-api
    ports:
      - "11434:11434"
    environment:
      - MODEL_NAME=gemma3:4b
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rag-net
